#ifndef PALETTE_GLSL
#define PALETTE_GLSL

// Global Tribe Totems //
const vec3 PALETTE_RED     = vec3(PALETTE_RED_R,     PALETTE_RED_G,     PALETTE_RED_B)     * (PALETTE_RED_I     / 255.0);
const vec3 PALETTE_ORANGE  = vec3(PALETTE_ORANGE_R,  PALETTE_ORANGE_G,  PALETTE_ORANGE_B)  * (PALETTE_ORANGE_I  / 255.0);
const vec3 PALETTE_YELLOW  = vec3(PALETTE_YELLOW_R,  PALETTE_YELLOW_G,  PALETTE_YELLOW_B)  * (PALETTE_YELLOW_I  / 255.0);
const vec3 PALETTE_LIME    = vec3(PALETTE_LIME_R,    PALETTE_LIME_G,    PALETTE_LIME_B)    * (PALETTE_LIME_I    / 255.0);
const vec3 PALETTE_GREEN   = vec3(PALETTE_GREEN_R,   PALETTE_GREEN_G,   PALETTE_GREEN_B)   * (PALETTE_GREEN_I   / 255.0);
const vec3 PALETTE_EMERALD = vec3(PALETTE_EMERALD_R, PALETTE_EMERALD_G, PALETTE_EMERALD_B) * (PALETTE_EMERALD_I / 255.0);
const vec3 PALETTE_CYAN    = vec3(PALETTE_CYAN_R,    PALETTE_CYAN_G,    PALETTE_CYAN_B)    * (PALETTE_CYAN_I    / 255.0);
const vec3 PALETTE_LTBLUE  = vec3(PALETTE_LTBLUE_R,  PALETTE_LTBLUE_G,  PALETTE_LTBLUE_B)  * (PALETTE_LTBLUE_I  / 255.0);
const vec3 PALETTE_BLUE    = vec3(PALETTE_BLUE_R,    PALETTE_BLUE_G,    PALETTE_BLUE_B)    * (PALETTE_BLUE_I    / 255.0);
const vec3 PALETTE_PURPLE  = vec3(PALETTE_PURPLE_R,  PALETTE_PURPLE_G,  PALETTE_PURPLE_B)  * (PALETTE_PURPLE_I  / 255.0);
const vec3 PALETTE_MAGENTA = vec3(PALETTE_MAGENTA_R, PALETTE_MAGENTA_G, PALETTE_MAGENTA_B) * (PALETTE_MAGENTA_I / 255.0);
const vec3 PALETTE_PINK    = vec3(PALETTE_PINK_R,    PALETTE_PINK_G,    PALETTE_PINK_B)    * (PALETTE_PINK_I    / 255.0);

#endif
